SELECT UPPER(MC.SEGMENT1)
  FROM APPS.MTL_ITEM_CATEGORIES MIC, APPS.MTL_CATEGORIES MC
 WHERE MIC.CATEGORY_SET_ID = 1100000505
   AND MIC.ORGANIZATION_ID = 1755
   AND MC.CATEGORY_ID = MIC.CATEGORY_ID
   AND MIC.INVENTORY_ITEM_ID = MPTDTV.INVENTORY_ITEM_ID), 'X') = 'HEAVY'