SELECT OOD.ORGANIZATION_CODE,
 MSI.SEGMENT1,
(SELECT CASE WHEN COUNT(*) > 0 THEN 'Y' ELSE 'N' END 
FROM APPS.MTL_CATEGORY_SETS MCS, 
APPS.MTL_CATEGORIES_B MCB, 
APPS.MTL_ITEM_CATEGORIES MIC 
WHERE MCS.CATEGORY_SET_NAME = 'FISCAL_CLASSIFICATION' 
AND MCS.CATEGORY_SET_ID = MIC.CATEGORY_SET_ID 
AND MCS.STRUCTURE_ID = MCB.STRUCTURE_ID 
AND MCB.CATEGORY_ID = MIC.CATEGORY_ID 
AND MIC.INVENTORY_ITEM_ID = MSI.INVENTORY_ITEM_ID 
AND MIC.ORGANIZATION_ID = MSI.ORGANIZATION_ID 
AND ROWNUM = 1) FISCAL_CLASSIFICATION, 
MSI.GLOBAL_ATTRIBUTE4 IND_PRODUTO,
CASE MSI.GLOBAL_ATTRIBUTE4 
WHEN 'A' THEN 'ATIVO FIXO' 
WHEN 'C' THEN 'COMPRADOS' 
WHEN 'E' THEN 'EMBALAGEM' 
WHEN 'F' THEN 'FABRICADOS' 
WHEN 'I' THEN 'INACABADO' 
WHEN 'M' THEN 'MATERIA-PRIMA' 
WHEN 'O' THEN 'OUTROS' 
WHEN 'S' THEN 'SERVICOS' 
WHEN 'U' THEN 'USO E CONSUMO' END IND_PRD_DESC,
TRANSLATE(PBR.DESC_ITEM_TRAD_PBR, CHR(9)||CHR(10)||CHR(13)||';',' ,') DESC_ITEM_TRAD_PBR,
TO_CHAR(MSI.CREATION_DATE,'DD/MM/YYYY') CREATION_DATE,
TO_CHAR(MSI.LAST_UPDATE_DATE,'DD/MM/YYYY') LAST_UPDATE_DATE 

FROM (SELECT MSIB.INVENTORY_ITEM_ID, TRIM(MSIB.ATTRIBUTE3) DESC_ITEM_TRAD_PBR 
FROM APPS.MTL_SYSTEM_ITEMS_B MSIB, 
APPS.ORG_ORGANIZATION_DEFINITIONS OODS 
WHERE MSIB.ENABLED_FLAG = 'Y' 
AND MSIB.ORGANIZATION_ID = OODS.ORGANIZATION_ID 
AND OODS.ORGANIZATION_CODE = 'PBR' 
AND MSIB.INVENTORY_ITEM_STATUS_CODE != 'INACTIVE' 
AND OODS.OPERATING_UNIT = 4330) PBR, 
APPS.MTL_SYSTEM_ITEMS_B MSI, 
(SELECT DISTINCT MMT.ORGANIZATION_ID, 
MMT.INVENTORY_ITEM_ID 
FROM APPS.MTL_MATERIAL_TRANSACTIONS MMT,
APPS.ORG_ORGANIZATION_DEFINITIONS OOD2 
WHERE MMT.TRANSACTION_DATE >= '01-FEB-24'
AND MMT.TRANSACTION_DATE <= '12-MAR-24'
AND MMT.ORGANIZATION_ID = OOD2.ORGANIZATION_ID AND OOD2.OPERATING_UNIT = 4330) MVT, 
APPS.ORG_ORGANIZATION_DEFINITIONS OOD 
WHERE PBR.INVENTORY_ITEM_ID = MSI.INVENTORY_ITEM_ID 
AND MSI.INVENTORY_ITEM_ID = MVT.INVENTORY_ITEM_ID 
AND MSI.ORGANIZATION_ID = MVT.ORGANIZATION_ID 
AND OOD.OPERATING_UNIT = 4330 
AND OOD.ORGANIZATION_ID = MVT.ORGANIZATION_ID;